In [10]:
## REQUESTS_HTML #########################
# pip install requests-html
# pip install pandas

#This block of code is used to find the table of data within the html file. 
import requests_html
import pandas as pd

URL = 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=1'

ses = requests_html.HTMLSession()
res = ses.get(URL)
html_table = res.html.find("table", first=True).html

df = pd.read_html(html_table)[11] # table found at index 11

In [2]:
#Here we are importing the necessare
## URLLIB + beautifulsoup #########################
# pip install pandas
# pip install beautifulsoup4
import urllib.request
from bs4 import BeautifulSoup
import pandas as pd

URL = 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=1'

with urllib.request.urlopen(URL) as response:
   html = response.read()
   
parser = BeautifulSoup(html, 'html.parser')
html_table = parser.find_all('table')[11].prettify()

df = pd.read_html(html_table)[0]

In [3]:
df

,X,Filing Date,Trade Date,Ticker,Company Name,Insider Name,Title,Trade Type,Price,Qty,Owned,ΔOwn,Value,1d,1w,1m,6m
0,NaN,2022-10-18 16:47:30,2022-10-18,SG,"Sweetgreen, Inc.",Shlossman Daniel,CMO,S - Sale,$20.00,-4000,244270,-2%,"-$80,000",NaN,NaN,NaN,NaN
1,NaN,2022-10-18 19:32:32,2022-10-18,JBL,Jabil Inc,Borges Steven D,"EVP, CEO, Regulated Industries",S - Sale,$62.00,-19695,187100,-10%,"-$1,221,090",NaN,NaN,NaN,NaN
2,NaN,2022-10-19 14:48:24,2022-10-18,VZIO,Vizio Holding Corp.,Amtran Technology Co. Ltd.,10%,S - Sale,$10.07,-40000,11180467,0%,"-$402,700",NaN,NaN,NaN,NaN
3,NaN,2022-10-19 14:56:38,2022-10-18,LLY,Eli Lilly & Co,Lilly Endowment Inc,10%,S - Sale,$334.03,-12042,103529293,0%,"-$4,022,377",NaN,NaN,NaN,NaN
4,NaN,2022-10-19 16:00:36,2022-10-18,AEHR,Aehr Test Systems,Spink Kenneth B.,"VP OF FINANCE, CFO",S - Sale,$18.65,-30000,127673,-19%,"-$559,500",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,2022-09-13 19:13:20,2022-09-12,DECK,Deckers Outdoor Corp,Powers David,"Pres,amp; CEO",S - Sale,$349.50,-2925,100972,-3%,"-$1,022,288",NaN,NaN,NaN,NaN
996,NaN,2022-09-13 19:53:46,2022-09-12,AVAV,Aerovironment Inc,Shackley Brian Charles,"VP, Chief Accounting Officer",S - Sale,$100.39,-500,3382,-13%,"-$50,195",NaN,NaN,NaN,NaN
997,NaN,2022-09-13 20:01:37,2022-09-12,BILL,"Bill.Com Holdings, Inc.",Lacerte Rene A.,"Pres, CEO",S - Sale,$175.05,-6248,2586300,0%,"-$1,093,709",NaN,NaN,NaN,NaN
998,NaN,2022-09-13 20:18:38,2022-09-12,CSCO,"Cisco Systems, Inc.",Martinez Maria,"EVP, COO",S - Sale,$46.40,-4674,274583,-2%,"-$216,878",NaN,NaN,NaN,NaN
999,NaN,2022-09-14 10:51:31,2022-09-12,USPH,U S Physical Therapy Inc /nv,Chapman Harry S,Dir,S - Sale,$80.50,-5000,22500,-18%,"-$402,500",NaN,NaN,NaN,NaN

In [4]:
url_lst_sales = []

for i in range(1,10):
    x='http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page={}'.format(i)
    url_lst_sales.append(x)

In [5]:
url_lst_sales

['http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=1',
 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=2',
 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=3',
 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=4',
 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=5',
 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=6',
 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=7',
 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=8',
 'http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page=9']

In [6]:
#picking up the remaining sale transactions that couldnt be retrieved due to a 9 page limit on the data
#..data is  03/02/2022 and before
for i in range(1,4):
    x='http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=365&fdr=&td=-1&tdr=01%2F01%2F2022+-+03%2F01%2F2022&fdlyl=&fdlyh=&daysago=&xs=1&excludeDerivRelated=1&vl=50&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=1000&page={}'.format(i)
    url_lst_sales.append(x)

In [7]:
pgs = [i for i in range(12)]
pgs

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [11]:
for i in pgs:
    x=url_lst_sales[i]
    res = ses.get(x)
    html_table = res.html.find("table", first=True).html
    exec('df{} = pd.read_html(html_table)[11]'.format(i))

In [17]:
df8

,X,Filing Date,Trade Date,Ticker,Company Name,Insider Name,Title,Trade Type,Price,Qty,Owned,ΔOwn,Value,1d,1w,1m,6m
0,M,2022-03-22 16:16:36,2022-03-18,RES,Rpc Inc,"Rollins Holding Company, Inc.",10%,S - Sale,$10.12,-685000,994785,-41%,"-$6,931,469",NaN,NaN,NaN,NaN
1,NaN,2022-03-22 16:18:10,2022-03-18,ZI,Zoominfo Technologies Inc.,Hyzer Peter Cameron,CFO,S - Sale,$60.00,-35893,1161638,-3%,"-$2,153,698",NaN,NaN,NaN,NaN
2,M,2022-03-22 16:18:03,2022-03-18,EMAN,Emagin Corp,Ginola Ltd,10%,S - Sale,$1.20,-65014,481668,-12%,"-$77,734",NaN,NaN,NaN,NaN
3,NaN,2022-03-22 16:17:43,2022-03-18,ZI,Zoominfo Technologies Inc.,Schuck Henry,"CEO, 10%",S - Sale,$60.00,-31328,16348698,0%,"-$1,879,774",NaN,NaN,NaN,NaN
4,NaN,2022-03-22 16:17:33,2022-03-18,AMZN,Amazon Com Inc,Selipsky Adam,CEO Amazon Web Services,S - Sale,"$3,200.00",-344,22365,-2%,"-$1,100,800",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,2022-03-08 18:34:48,2022-03-04,AMK,"Assetmark Financial Holdings, Inc.",Kim Michael,"Pres, CCO",S - Sale,$22.30,-4114,353514,-1%,"-$91,742",NaN,NaN,NaN,NaN
996,NaN,2022-03-08 18:46:55,2022-03-04,STX,Seagate Technology Holdings Plc,Luczo Stephen J,Dir,S - Sale,$103.27,-50000,225941,-18%,"-$5,163,235",NaN,NaN,NaN,NaN
997,NaN,2022-03-08 19:13:27,2022-03-04,AR,Antero Resources Corp,Clark Robert J,Dir,S - Sale,$25.00,-10000,93107,-10%,"-$250,000",NaN,NaN,NaN,NaN
998,M,2022-03-08 20:48:37,2022-03-04,IPI,"Intrepid Potash, Inc.",Clearway Capital Management LLC,10%,S - Sale,$68.34,-183917,1406083,-12%,"-$12,568,051",NaN,NaN,NaN,NaN
999,NaN,2022-03-08 21:00:16,2022-03-04,KLXE,"Klx Energy Services Holdings, Inc.",Baker Christopher J.,See Remarks,S - Sale,$10.00,-28585,178520,-14%,"-$285,953",NaN,NaN,NaN,NaN

In [16]:
#data from df9 overlaps on 9 rows with df10 
df9_new= df9.iloc[10:]

In [13]:
df9

,X,Filing Date,Trade Date,Ticker,Company Name,Insider Name,Title,Trade Type,Price,Qty,Owned,ΔOwn,Value,1d,1w,1m,6m
0,NaN,2022-03-02 10:18:05,2022-03-02,DHIL,Diamond Hill Investment Group Inc,Meyer Paula R,Dir,S - Sale,$197.00,-500,1879,-21%,"-$98,500",NaN,NaN,NaN,NaN
1,NaN,2022-03-02 12:39:56,2022-03-02,DTE,Dte Energy Co,Harris Joi M.,"Pres, COO - DTE Gas Company",S - Sale,$120.97,-1650,13741,-11%,"-$199,601",NaN,NaN,NaN,NaN
2,NaN,2022-03-02 16:35:15,2022-03-02,RM,Regional Management Corp.,Dunn Michael R,Dir,S - Sale,$49.94,-12000,95761,-11%,"-$599,280",NaN,NaN,NaN,NaN
3,NaN,2022-03-02 17:01:52,2022-03-02,ACLS,Axcelis Technologies Inc,Brewer Kevin J,"EVP, CFO",S - Sale,$70.89,-8636,58125,-13%,"-$612,206",NaN,NaN,NaN,NaN
4,NaN,2022-03-02 17:46:33,2022-03-02,WTS,Watts Water Technologies Inc,Melhem Elie,"Pres- APAC, M. East, Afr.",S - Sale,$145.04,-5600,12977,-30%,"-$812,224",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,2022-02-15 19:22:53,2022-02-15,PLYA,Playa Hotels & Resorts N.V.,Peterson Karl Mr.,Dir,S - Sale,$8.52,-30000,3239033,-1%,"-$255,600",NaN,NaN,NaN,NaN
996,NaN,2022-02-16 11:46:25,2022-02-15,TSE,Trinseo Plc,M&g Investment Management Ltd,10%,S - Sale,$57.57,-3000,7628044,0%,"-$172,710",NaN,NaN,NaN,NaN
997,NaN,2022-02-16 12:03:40,2022-02-15,CSL,Carlisle Companies Inc,Berlin John E,"Pres, CIT",S - Sale,$236.94,-6192,30693,-17%,"-$1,467,143",NaN,NaN,NaN,NaN
998,NaN,2022-02-16 13:19:59,2022-02-15,RMBS,Rambus Inc,Shinn John,"SVP, GC",S - Sale,$26.81,-10073,28779,-26%,"-$270,105",NaN,NaN,NaN,NaN
999,NaN,2022-02-16 14:29:52,2022-02-15,IIVI,II-Vi Inc,Mattera Vincent D Jr,CEO,S - Sale,$70.00,-2000,422849,0%,"-$140,000",NaN,NaN,NaN,NaN

In [14]:
df8

,X,Filing Date,Trade Date,Ticker,Company Name,Insider Name,Title,Trade Type,Price,Qty,Owned,ΔOwn,Value,1d,1w,1m,6m
0,M,2022-03-22 16:16:36,2022-03-18,RES,Rpc Inc,"Rollins Holding Company, Inc.",10%,S - Sale,$10.12,-685000,994785,-41%,"-$6,931,469",NaN,NaN,NaN,NaN
1,NaN,2022-03-22 16:18:10,2022-03-18,ZI,Zoominfo Technologies Inc.,Hyzer Peter Cameron,CFO,S - Sale,$60.00,-35893,1161638,-3%,"-$2,153,698",NaN,NaN,NaN,NaN
2,M,2022-03-22 16:18:03,2022-03-18,EMAN,Emagin Corp,Ginola Ltd,10%,S - Sale,$1.20,-65014,481668,-12%,"-$77,734",NaN,NaN,NaN,NaN
3,NaN,2022-03-22 16:17:43,2022-03-18,ZI,Zoominfo Technologies Inc.,Schuck Henry,"CEO, 10%",S - Sale,$60.00,-31328,16348698,0%,"-$1,879,774",NaN,NaN,NaN,NaN
4,NaN,2022-03-22 16:17:33,2022-03-18,AMZN,Amazon Com Inc,Selipsky Adam,CEO Amazon Web Services,S - Sale,"$3,200.00",-344,22365,-2%,"-$1,100,800",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,2022-03-08 18:34:48,2022-03-04,AMK,"Assetmark Financial Holdings, Inc.",Kim Michael,"Pres, CCO",S - Sale,$22.30,-4114,353514,-1%,"-$91,742",NaN,NaN,NaN,NaN
996,NaN,2022-03-08 18:46:55,2022-03-04,STX,Seagate Technology Holdings Plc,Luczo Stephen J,Dir,S - Sale,$103.27,-50000,225941,-18%,"-$5,163,235",NaN,NaN,NaN,NaN
997,NaN,2022-03-08 19:13:27,2022-03-04,AR,Antero Resources Corp,Clark Robert J,Dir,S - Sale,$25.00,-10000,93107,-10%,"-$250,000",NaN,NaN,NaN,NaN
998,M,2022-03-08 20:48:37,2022-03-04,IPI,"Intrepid Potash, Inc.",Clearway Capital Management LLC,10%,S - Sale,$68.34,-183917,1406083,-12%,"-$12,568,051",NaN,NaN,NaN,NaN
999,NaN,2022-03-08 21:00:16,2022-03-04,KLXE,"Klx Energy Services Holdings, Inc.",Baker Christopher J.,See Remarks,S - Sale,$10.00,-28585,178520,-14%,"-$285,953",NaN,NaN,NaN,NaN

In [19]:
trade_df = pd.concat([df0,df1, df2, df3, df4, df5, df6, df7,df8,df9,df10,df11], ignore_index=True, sort=False)

In [162]:
#trade_df.columns = [c.replace(' ', '_') for c in trade_df.columns]

In [20]:
#check number of rows
len(trade_df)

11565

In [62]:
#reassign
sales_df=trade_df

In [63]:
#Now we add new columns to clean them a
sales_df['delta_own']=sales_df['ΔOwn']
sales_df['delta_own']=sales_df['delta_own'].map(lambda x: x.lstrip('+->').rstrip(''))
sales_df['delta_own'] = sales_df['delta_own'].str.rstrip('%').astype('float') / 100.0

sales_df['trade_value']=sales_df['Value']
sales_df['trade_value']=sales_df['trade_value'].map(lambda x: x.lstrip('+-').rstrip(''))
sales_df['trade_value']=sales_df['trade_value'].str.replace('$', '')
sales_df['trade_value']=sales_df['trade_value'].str.replace(',', '')
sales_df['trade_value']=sales_df['trade_value'].astype('float')


#Could also use To 
#remove all substring "a" from column A: df["A"].str.replace("a","")
#To remove all substrings "a" or "b": df["A"].str.replace("[ab]","")

In [ ]:
sales_df['price_new']=sales_df['Price']
sales_df['price_new']=sales_df['price_new'].str.replace('$', '')
sales_df['price_new']=sales_df['price_new'].str.replace(',', '')
sales_df['price_new']=sales_df['price_new'].astype('float')

In [64]:
#we can verify the types with a new column or just execute sales_df.dtypes
sales_df['delta_own_type'] = sales_df['delta_own'].apply(lambda x: type(x).__name__)
sales_df['trade_value_type'] = sales_df['trade_value'].apply(lambda x: type(x).__name__)
sales_df['price_new_type'] = sales_df['price_new'].apply(lambda x: type(x).__name__)

,X,Filing Date,Trade Date,Ticker,Company Name,Insider Name,Title,Trade Type,Price,Qty,Owned,ΔOwn,Value,1d,1w,1m,6m,delta_own,trade_value
0,NaN,2022-10-14 16:34:47,2022-10-14,ACI,"Albertsons Companies, Inc.",Kimco Realty Corp,See Remarks,S - Sale,$26.18,-11500000,28338105,-29%,"-$301,070,000",NaN,NaN,NaN,NaN,-29%,"-$301,070,000"
1,NaN,2022-10-13 19:54:58,2022-10-13,TEAM,Atlassian Corp,Farquhar Scott,"Co-CEO, Co-Founder, 10%",S - Sale,$196.62,-8614,465156,-2%,"-$1,693,648",NaN,NaN,NaN,NaN,-2%,"-$1,693,648"
2,NaN,2022-10-13 19:54:48,2022-10-13,TEAM,Atlassian Corp,Cannon-Brookes Michael,"Co-CEO, Co-Founder, 10%",S - Sale,$196.62,-8614,465156,-2%,"-$1,693,653",NaN,NaN,NaN,NaN,-2%,"-$1,693,653"
3,NaN,2022-10-14 16:00:10,2022-10-13,SEAS,"Seaworld Entertainment, Inc.",Swanson Marc,CEO,S - Sale,$48.75,-4000,162129,-2%,"-$195,000",NaN,NaN,NaN,NaN,-2%,"-$195,000"
4,NaN,2022-10-14 16:30:21,2022-10-13,ABNB,"Airbnb, Inc.",Gebbia Joseph,"Dir, 10%",S - Sale,$110.13,-250000,1377151,-15%,"-$27,531,704",NaN,NaN,NaN,NaN,-15%,"-$27,531,704"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11550,M,2022-01-05 21:20:13,2022-01-03,ITOS,"Iteos Therapeutics, Inc.","Boxer Capital, LLC","Dir, 10%",S - Sale,$46.54,-700000,0,-100%,"-$32,575,642",NaN,NaN,NaN,NaN,-100%,"-$32,575,642"
11551,NaN,2022-01-05 21:20:11,2022-01-03,STEM,"Stem, Inc.",Triplett Mark William,COO,S - Sale,$19.22,-5000,20801,-19%,"-$96,113",NaN,NaN,NaN,NaN,-19%,"-$96,113"
11552,NaN,2022-01-06 16:37:22,2022-01-03,CRNX,"Crinetics Pharmaceuticals, Inc.",Betz Stephen F.,Chief Scientific Officer,S - Sale,$28.02,-7168,133043,-5%,"-$200,847",NaN,NaN,NaN,NaN,-5%,"-$200,847"
11553,M,2022-01-12 17:50:31,2022-01-03,CVEO,Civeo Corp,Torgerson Lance,10%,S - Sale,$19.72,-20507,1849090,-1%,"-$404,301",NaN,NaN,NaN,NaN,-1%,"-$404,301"
11554,NaN,2022-01-21 17:57:18,2022-01-03,SNDR,"Schneider National, Inc.",Geyer David L,"EVP, Pres Transp., Log.",S - Sale,$26.82,-16000,168684,-9%,"-$429,120",NaN,NaN,NaN,NaN,-9%,"-$429,120"

In [81]:
#save sales_df for record 
x= 'insidersales_ytd_{}.csv'.format(pd.to_datetime("today").strftime("%m.%d.%Y"))
sales_df.to_csv(x, index=False)